backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/projects"
public_folder: "../../assets/projects"
collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "src/content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Category (Primary)",
          name: "category",
          widget: "select",
          options:
            [
              { label: "Agricultural", value: "agricultural" },
              { label: "Industrial", value: "industrial" },
              { label: "Recladding", value: "recladding" },
              { label: "Groundworks", value: "groundworks" },
              { label: "New Build", value: "new-build" },
            ],
        }
      - {
          label: "Related Services",
          name: "services",
          widget: "select",
          multiple: true,
          required: false,
          options:
            [
              { label: "Agricultural Buildings", value: "agricultural" },
              { label: "Industrial Buildings", value: "industrial" },
              { label: "Groundworks & Civils", value: "groundworks" },
              { label: "Steel Erection", value: "steel-erection" },
            ],
        }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Gallery Images",
          name: "gallery",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
        }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "Order", name: "order", widget: "number", default: 100 }
